AWSTemplateFormatVersion: '2010-09-09'
Description: LifeSync360 CloudWatch Log Groups

Resources:
  PlatformLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/lifesync-platform
      RetentionInDays: 30

  AdminLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/lifesync-admin
      RetentionInDays: 30

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/lifesync-gcp-result-ingest
      RetentionInDays: 14

  CodeBuildPlatformLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /codebuild/lifesync-platform
      RetentionInDays: 14

  CodeBuildAdminLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /codebuild/lifesync-admin
      RetentionInDays: 14
