all:
  children:
    mysql:
      hosts:
        ls-db:
          ansible_host: 192.168.56.11
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyJump=ansible@100.91.12.14'
    tokenization:
      hosts:
        ls-token:
          ansible_host: 192.168.56.12
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyJump=ansible@100.91.12.14'
          mysql_vm_ip: 192.168.56.11
          mysql_app_user: lifesync
          mysql_app_password: "{{ vault_mysql_app_password }}"
    private_api:
      hosts:
        ls-api:
          ansible_host: 100.91.12.14
          pii_aes_key: "{{ vault_pii_aes_key }}"
          mysql_vm_ip: 192.168.56.11
          mysql_app_user: lifesync
          mysql_app_password: "{{ vault_mysql_app_password }}"
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3
