AWSTemplateFormatVersion: '2010-09-09'
Description: LifeSync360 Internet Gateway

Resources:
  Igw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: lifesync-igw

  VpcAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !ImportValue lifesync-vpc-VpcId
      InternetGatewayId: !Ref Igw

Outputs:
  IgwId:
    Value: !Ref Igw
    Export:
      Name: lifesync-igw-IgwId
