AWSTemplateFormatVersion: '2010-09-09'
Description: LifeSync360 CodeCommit Repositories

Resources:
  PlatformRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: lifesync360-platform
      RepositoryDescription: lifesync360 platform service

  AdminRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: lifesync360-admin
      RepositoryDescription: lifesync360 admin platform

Outputs:
  PlatformCloneUrl:
    Value: !GetAtt PlatformRepo.CloneUrlHttp
    Export:
      Name: lifesync-codecommit-PlatformCloneUrl
  AdminCloneUrl:
    Value: !GetAtt AdminRepo.CloneUrlHttp
    Export:
      Name: lifesync-codecommit-AdminCloneUrl
  PlatformRepoArn:
    Value: !GetAtt PlatformRepo.Arn
    Export:
      Name: lifesync-codecommit-PlatformRepoArn
  AdminRepoArn:
    Value: !GetAtt AdminRepo.Arn
    Export:
      Name: lifesync-codecommit-AdminRepoArn
